### ISSUE TITLE
BasicXUnitTests.cs file does not build - Unable to use Common.Configuration with Create(TestOptions)

### ISSUE THREAD

**Issue by mrkylerhodes** [Jarga/Alias#6]
Here's the message I'm getting when I try to build the Aliases Example solution: 
`Argument 1: cannot convert from 'Aliases.TestExecutors.XUnit.XUnitTestOutput' to 'Aliases.Common.Configuration.TestOptions'	Aliases.TestExecutors.XUnit`

It looks like the problem is coming from Aliases.Common.Configuration line 20 where ITestConfiguration Create is no longer using multiple values and instead is using a TestOptions variable.

In my code (which is very similar to ExampleBasicConfig.cs) when I run my tests it gives the message:
`Additional information: Method not found: 'Aliases.Common.Configuration.ITestConfiguration Aliases.Common.Configuration.ITestConfiguration.Create(Aliases.Common.Output.ITestOutput, System.String, System.Nullable`1<Aliases.Common.Shared.Enumerations.EnvironmentType>,
Aliases.Common.Shared.ITestableWebPage)'.`

In order to get my code to run successfully, I had to revert back to version 2.0.2

Thanks,
Kyle

**Comment by Jarga** [comment]
Looking at fixing those projects now.  Along with updating everything to work with the new .NET Core version of Selenium.  A temporary fix for you should be to use the following syntax instead of what was there:

`TestConfiguration = new SeleniumTestConfiguration().Create(new TestOptions()
            {
                TestOutput = new XUnitTestOutput(output)
            });`

The Create(...) contract changed from raw parameters to an object, but everything else should still work without extra options.
